FROM node:18-alpine3.15

# Set working directory
RUN mkdir -p /var/www/apiFarma
WORKDIR /var/www/apiFarma

# Copiar el directorio y su contenido
COPY . ./var/www/apiFarma
COPY package.json tsconfig.json tsconfig.build.json /var/www/apiFarma/
RUN yarn install --prod
RUN yarn build


# Dar permiso para ejecutar la applicación
RUN adduser --disabled-password farmauser
RUN chown -R farmauser:farmauser /var/www/apiFarma
USER farmauser

# Limpiar el caché
RUN yarn cache clean --force

EXPOSE 3000

CMD [ "yarn","start" ]