version: '3'

services:
  db:
    container_name: apifirma
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # apifarma-mongodb:
  #   container_name: apifarma-mongodb
  #   image: mongo:5
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGODB_DATABASE: apiFarma
  #   volumes:
  #     - ./mongo:/data/db